In [1]:
weight = 0.1

def neural_network(input, weight):
    prediction = input * weight
    
    return prediction

number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


In [6]:
weights = [0.1, 0.2, 0]

def w_sum(a, b):
    assert(len(a) == len(b))
    
    output = 0
    
    for i in range(len(a)):
        output += (a[i] * b[i])
        
    return output

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

pred

0.9800000000000001

In [2]:
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    pred = input.dot(weights)
    
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)

pred

0.9800000000000001

In [4]:
weights = [0.3, 0.2, 0.9]

def ele_mul(number, vector):
    output = [0, 0, 0]
    
    assert(len(output) == len(vector))
    
    for i in range(len(vector)):
        output[i] = number * vector[i]
        
    return output

def neural_network(input, weights):
    pred = ele_mul(input, weights)
    
    return pred

wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input, weights)

pred

[0.195, 0.13, 0.5850000000000001]

In [5]:
weights = [[0.1, 0.1, -0.3],
          [0.1, 0.2, 0.0],
          [0.0, 1.3, 0.1]]

def w_sum(a, b):
    assert(len(a) == len(b))
    
    output = 0
    
    for i in range(len(a)):
        output += (a[i] * b[i])
        
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]
    
    assert(len(vect) == len(output))
    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
        
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

pred

[0.555, 0.9800000000000001, 0.9650000000000001]

In [8]:
ih_wgt = [[0.1, 0.2, -0.1],
         [-0.1, 0.1, 0.9],
         [0.1, 0.4, 0.1]]

hp_wgt = [[0.3, 1.1, -0.3],
         [0.1, 0.2, 0.0],
         [0.0, 1.3, 0.1]]

weights = [ih_wgt, hp_wgt]

def w_sum(a, b):
    assert(len(a) == len(b))
    
    output = 0
    
    for i in range(len(a)):
        output += (a[i] * b[i])
        
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]
    
    assert(len(vect) == len(output))
    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
        
    return output

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

pred

[0.21350000000000002, 0.14500000000000002, 0.5065]

In [10]:
import numpy as np

ih_wgt = np.array([[0.1, 0.2, -0.1],
         [-0.1, 0.1, 0.9],
         [0.1, 0.4, 0.1]]).T

hp_wgt = np.array([[0.3, 1.1, -0.3],
         [0.1, 0.2, 0.0],
         [0.0, 1.3, 0.1]]).T

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)

pred

array([0.2135, 0.145 , 0.5065])

In [19]:
import numpy as np

a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[0, 1, 2, 3],
             [4, 5, 6, 7]])
d = np.zeros((2, 4))
e = np.random.rand(2, 5)

a, b, c, d, e

(array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[0.72493732, 0.86392579, 0.47195173, 0.5397061 , 0.36416751],
        [0.71304689, 0.11675171, 0.97825553, 0.30191647, 0.97033653]]))

In [16]:
a * 0.1, c * 0.2, a * b, a * b * 0.2, a * c

(array([0. , 0.1, 0.2, 0.3]),
 array([[0. , 0.2, 0.4, 0.6],
        [0.8, 1. , 1.2, 1.4]]),
 array([ 0,  5, 12, 21]),
 array([0. , 1. , 2.4, 4.2]),
 array([[ 0,  1,  4,  9],
        [ 0,  5, 12, 21]]))

In [17]:
a * e

ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [20]:
a = np.zeros((1, 4))
b = np.zeros((4, 3))

c = a.dot(b)
c.shape

(1, 3)

In [21]:
a = np.zeros((2, 4))
b = np.zeros((4, 3))

c = a.dot(b)
print(c.shape)

e = np.zeros((2, 1))
f = np.zeros((1, 3))

g = e.dot(f)
print(g.shape)

h = np.zeros((5, 4)).T
i = np.zeros((5, 6))

j = h.dot(i)
print(j.shape)

h = np.zeros((5, 4))
i = np.zeros((5, 6))
j = h.dot(i)
print(j.shape)

(2, 3)
(2, 3)
(4, 6)


ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)