In [130]:
# Your First Deep Neural Netwok
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

alpha = 0.1
hidden_size = 4
street_lights = np.array([[1, 0, 1],
                          [0, 1, 1],
                          [0, 0, 1],
                          [1, 1, 1]])
# street_lights = np.array([[1, 0, 1]])
walk_vs_stop = np.array([[1, 1, 0, 0]]).T

# weights_0_1 = 2*np.random.random((3, hidden_size)) - 1
weights_0_1 = np.random.random((3, hidden_size))
weights_1_2 = np.random.random((hidden_size, 1))
debug = True

def condition(iter):
    return iter % 100 == 0 and False or (iter > 596)

def inner_condition(iter):
    return iter >= 0

for iter in range(600):
    layer_2_error = 0
    for i in range(len(street_lights)):
        layer_0 = street_lights[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        
        layer_2_delta = (walk_vs_stop[i] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
        
        if (debug and condition(iter) and inner_condition(i)):
            print('Iteration Number is ' + str(iter))
            print(str(i) + '| ' + 'Res: ' + str(layer_2) + ', Expected: ' + str(walk_vs_stop[i]))
            print(str(i) + '| ' + 'Weights 1 to 2 BEFORE:\n' + str(weights_1_2))
            print(str(i) + '| ' + 'Weights 0 to 1 BEFORE:\n' + str(weights_0_1), end = '\n\n')
            print(str(i) + '| ' + 'Layer 2 Delta: ' + str(layer_2_delta))
            print(str(i) + '| ' + 'Layer 1 Delta: ' + str(layer_1_delta), end='\n\n')
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
        
        if (debug and condition(iter) and inner_condition(i)):
            print(str(i) + '| ' + 'Weights 1 to 2 AFTER:\n' + str(weights_1_2))
            print(str(i) + '| ' + 'Weights 0 to 1 AFTER:\n' + str(weights_0_1))
        
    if (condition(iter)):
        print('Error: ' + str(layer_2_error), end='\n\n\n\n')

Iteration Number is 597
0| Res: [[0.42022892]], Expected: [1]
0| Weights 1 to 2 BEFORE:
[[0.04650027]
 [0.44884841]
 [0.04431111]
 [0.28972683]]
0| Weights 0 to 1 BEFORE:
[[ 0.06378856  0.12421138 -0.09360469 -0.10007943]
 [ 0.02633233  0.00691769  0.02970878  0.04162395]
 [ 0.01921716  0.57427961  0.10213918  0.45377254]]

0| Layer 2 Delta: [[0.57977108]]
0| Layer 1 Delta: [[0.02695951 0.26022933 0.0256903  0.16797524]]

0| Weights 1 to 2 AFTER:
[[0.0513127 ]
 [0.4893449 ]
 [0.04480592]
 [0.31023294]]
0| Weights 0 to 1 AFTER:
[[ 0.06648451  0.15023431 -0.09103566 -0.0832819 ]
 [ 0.02633233  0.00691769  0.02970878  0.04162395]
 [ 0.02191311  0.60030254  0.10470821  0.47057006]]
Iteration Number is 597
1| Res: [[0.46453785]], Expected: [1]
1| Weights 1 to 2 BEFORE:
[[0.0513127 ]
 [0.4893449 ]
 [0.04480592]
 [0.31023294]]
1| Weights 0 to 1 BEFORE:
[[ 0.06648451  0.15023431 -0.09103566 -0.0832819 ]
 [ 0.02633233  0.00691769  0.02970878  0.04162395]
 [ 0.02191311  0.60030254  0.10470821  0