In [5]:
# Your First Deep Neural Netwok
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

alpha = 0.2
hidden_size = 4
street_lights = np.array([[1, 0, 1],
                          [0, 1, 1],
                          [0, 0, 1],
                          [1, 1, 1]])
walk_vs_stop = np.array([[1, 1, 0, 0]]).T

weights_0_1 = np.random.random((3, hidden_size))
weights_1_2 = np.random.random((hidden_size, 1))

print('Weights 0 to 1:\n' + str(weights_0_1))
print('Weights 1 to 2:\n' + str(weights_1_2))

layer_0 = street_lights[0]
layer_1 = relu(np.dot(layer_0, weights_0_1))
layer_2 = np.dot(layer_1, weights_1_2)

Weights 0 to 1:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]]
Weights 1 to 2:
[[0.20445225]
 [0.87811744]
 [0.02738759]
 [0.67046751]]
Np dot: [0.81378948 1.25914123 0.41930889 0.98755207]
